name: jaffle_shop
version: '0.1'
config-version: 2
profile: 'salesforce'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  jaffle_shop:
    +materialized: table
flags:
  require_generic_test_arguments_property: true